# 11. C# 6.0

## 11.8 예외 필터

```cs
class Program
{
    static void Main(string[] args)
    {
        string filePath = @"c:\temp\test.txt";

        try { string txt = File.ReadAllText(filePath); }
        catch (FileNotFoundException e) { WriteLine(e.ToString()); }
    }
}
```

* 지정한 파일이 없는 경우 무조건 FileNotFountException 예외 핸들러가 선택되어 실행된다.
* when 예약어와 함께 조건을 명시할 수 있다.

```cs
static void Main(string[] args)
{
    string filePath = @"c:\temp\test.txt";

    try { string txt = File.ReadAllText(filePath); }
    catch (FileNotFoundException e)
    when (filePath.IndexOf("temp") != -1)
    {
        WriteLine(e.ToString());
    }
}
```

* 메서드로 분리하는 것도 가능하다.

```cs
class Program
{
    static void Main(string[] args)
    {
        string filePath = @"c:\temp\test.txt";

        try { string txt = File.ReadAllText(filePath); }
        catch (FileNotFoundException e)
        when (SwallowWhenTempFile(filePath))
        {
            WriteLine(e.ToString());
        }
    }

    static bool SwallowWhenTempFile(string filePath)
    {
        return filePath.IndexOf("temp") != -1;
    }
}
```

* 예외 필터의 조건식이 실행되는 시점은 아직 예외 처리 핸들러가 실행되는 시점이 아니기 때문에 예외가 발생한 시점의 호출 스택(Call stack)이 그대로 보존되어 있다.
* 그래서 기존 예외 처리 구조에 영향을 주지 않고도 부가적인 작업을 할 수 있다.

```cs
try { /* 코드 */ }
catch (Exception e) when (Log(e))
{
    // 이 코드는 절대로 실행되지 않는다.
}

bool Log(Exception e)
{
    WriteLine(e.ToString());
    return false;
    // true를 return하면 catch 블럭이 실행된다.
}

```

* 기존 예외 처리 구문에서는 동일한 예외 타입의 catch 구문을 여러 개 두는 것이 불가능했지만 예외 필터를 사용하면 가능하다.

## 11.9 catch/finally 블록 내에서 await 사용 가능

```cs
class Program
{
    static void Main(string[] args)
    {
        ProcessFileAsync();
        ReadLine();
    }

    private static async void ProcessFileAsync()
    {
        FileStream fs = null;

        try
        {
            fs = new FileStream(
                "test.txt", FileMode.Open, FileAccess.Read);
            byte[] contents = new byte[1024];
            await fs.ReadAsync(contents, 0, contents.Length);
            WriteLine("ReadAsync Called!");
        }
        catch (Exception e) { await LogAsync(e); }
        finally { await CloseAsync(fs); }
    }

    static Task LogAsync(Exception e)
    {
        return Task.Factory.StartNew(
            () => { WriteLine("Log Async Called!"); });
    }

    static Task CloseAsync(FileStream fs)
    {
        return Task.Factory.StartNew(
            () =>
            {
                WriteLine("Close Async Called!");
                if (fs != null) { fs.Close(); }
            });
    }
}
```

## 11.10 컬렉션 초기화 구문에 확장 메서드로 정의한 Add 지원

* 다음의 NaturalNumber 타입은 `ICollection<T>` 인터페이스를 구현하지 않았으므로 컬렉션 초기화 구문을 사용할 수 없어 컴파일 시에 오류가 발생한다.

```cs
namespace ConsoleApp1
{
    public class NaturalNumber : IEnumerable
    {
        List<int> numbers = new List<int>();
        public List<int> Numbers { get { return numbers; } }
        IEnumerator IEnumerable.GetEnumerator()
        {
            return numbers.GetEnumerator();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            NaturalNumber numbers = new NaturalNumber() { 0, 1, 2, 3, 4 };
            // NaturalNumber에는 Add에 대한 정의가 포함되어 있지 않아 컴파일 오류
            foreach (var item in numbers) { WriteLine(item); }
        }
    }
}
```

* C# 6.0에는 Add 메서드를 `ICollection<T>` 인터페이스가 없다면 확장 메서드로도 구현되어 있는지 다시 한번 더 찾는 기능을 추가했다.

```cs
public static class NaturalNumberExtension
{
    public static void Add(this NaturalNumber instance, int number)
    {
        instance.Numbers.Add(number);
    }
}
```

## 11.11 #pragma의 CS 접두사 지원

* 기존에는 경고를 끄려면 CS를 뺀 숫자만 넣어야 했다.

```cs
#progma warning disable 0168
```

* C# 6.0부터는 컴파일러 메시지 그대로 CS0168을 사용할 수 있다.

```cs
#progma warning disable CS0168
```